### ISSUE TITLE
Make 'nvim-ghost' more quiet

### ISSUE THREAD

**Issue by hereGittyGitty** [subnut/nvim-ghost.nvim#38]
Hi there,

first of all, thanks a lot for the plugin of course. I have one thing that keeps me from using it though:

Whenever I start my first `nvim` instance I always get the messages
```
[nvim-ghost] Could not connect to localhost:4001
[nvim-ghost] Could not connect to localhost:4001
[nvim-ghost] Servers started
```
Dunno what the first two messages are about.

Whenever I start another `nvim` instance I always get the message:
```
[nvim-ghost] Server running
```

Is there a way to stop _nvim-ghost.nvim_ from "polluting" my echo area every time I start `nvim`, besides commenting these lines out and using `let g:nvim_ghost_use_script = 1` etc. (which seems not to work)?

If you need any more input just ask. Thx

**Comment by subnut** [comment]
Checkout the `super-quiet-mode` branch, and add the following line to your `init.vim` -
```vim
let $NVIM_GHOST_SUPER_QUIET = 1
```

**Comment by hereGittyGitty** [comment]
Hi,

does what I was was looking for... thank you very much.

Just one thing. I still get one of the
```
[nvim-ghost] Could not connect to localhost:4001
```
messages. Beside the fact that these kind of messages should not be silenced, could you think of reason why it does appear? I am using the _vim_/_neovim_ built in package support
```
:h packages
```
If I am the only one with this problem: don't worry about it.

I can also create a new ticket if you think that this might be a problem affecting more people.

Once again, thx a lot for the fast solution for this ticket.

**Comment by subnut** [comment]
> Just one thing. I still get one of the
> 
> ```
> [nvim-ghost] Could not connect to localhost:4001
> ```
> 
> messages.

This message shouldn't have appeared.

**Comment by subnut** [comment]
@hereGittyGitty 

`git pull` the latest commit of the `super-quiet-mode` branch. Then change this line in your `init.vim` -
```vim
let $NVIM_GHOST_SUPER_QUIET = 1
```
to this -
```vim
let g:nvim_ghost_super_quiet = 1
```

Let me know if the `Could not connect` message still appears

**Comment by hereGittyGitty** [comment]
Yes, it's nice and quiet now. :)
 thx a lot.

**Comment by hereGittyGitty** [comment]
Hi,
I am afraid I have to tell you that the problem with the 
```
[nvim-ghost] Could not connect to localhost:4001
```
message still persists but does not appear every time and only when starting the first `nvim` instance. I guess I was just lucky when testing it for the first time.

Running _neovim_ with `nvim -V9` gave me the following output in addition to the output when that message from above did not appear:
```
Error detected while processing function nvim_ghost#request_focus[1]..<SNR>351_send_GET_request:
line   21:
connection failed: connection refused
[nvim-ghost] Could not connect to localhost:4001
```

Hope that helps...

**Comment by subnut** [comment]
- [ ] Are you using the latest commit 17a574a?
- [ ] Have you added `let g:nvim_ghost_super_quiet = 1` to your `init.vim`?

---

> does not appear every time and only when starting the first nvim instance

Let me explain. The plugin depends upon a daemon running on the background. The first time you run nvim after a reboot, the daemon isn't running. So, when it tries to connect to the daemon, it can't. Since it can't connect, so the error is shown.

Since nvim wasn't able to connect to the daemon, it starts up a daemon. The daemon keeps running even after the nvim instance is closed. So, the subsequent nvim instances have no problem to connect to the daemon, so the error message isn't shown.

---

To replicate the error everytime you start nvim, you need to kill the server every time you exit nvim (by calling `:call nvim_ghost#kill_server()`). So, add the following line to your `init.vim`
```vim
autocmd nvim_ghost VimLeavePre * call nvim_ghost#kill_server()
```

**Comment by hereGittyGitty** [comment]
- I am definitely on the latest commit (Looks like you added one yesterday but i tried that one too)
- I have definitely added `let g:nvim_ghost_super_quiet = 1` to my `init.vim`

I just did a screen recording to show you what i mean:
![demo](https://user-images.githubusercontent.com/2407498/126078382-4aa9cdc6-1efa-4ef2-84fe-9008a64dee28.gif)

Hope that helps.

**Comment by subnut** [comment]
Huh. That's fishy. 🧐   
Thanks for the GIF. It showed me a bigger problem. 

Anyway, the message was appearing due to a wrong condition in my code 😅. See this -
```diff
diff --git a/autoload/nvim_ghost.vim b/autoload/nvim_ghost.vim
index 417b3ba..84b2624 100644
--- a/autoload/nvim_ghost.vim
+++ b/autoload/nvim_ghost.vim
@@ -51,7 +51,7 @@ function! s:send_GET_request(url) abort "{{{1
   let v:errmsg = ''
   silent! let l:connection = sockconnect('tcp', l:url, l:opts)
   if v:errmsg !=# '' || l:connection == 0
-    if g:nvim_ghost_super_quiet != 0
+    if g:nvim_ghost_super_quiet != 1
       echohl WarningMsg
       echom '[nvim-ghost] Could not connect to ' . l:url
       echohl None
```
I will include this in a commit.

----

The _bigger_ issue I was talking about is.... every time the first `nvim` instance is closed, the daemon gets killed. Whereas it should have kept running. 

The reason I couldn't catch this bug was that, I always run nvim with
```vim
let g:nvim_ghost_logging_enabled = 1
```
which seems to workaround this bug somehow! ***Hmmmmm....***

**Comment by subnut** [comment]
Fixed it!

Tryout the latest `main` branch. Use the config -
```vim
let g:nvim_ghost_super_quiet = 1
```

Let me know if the bug is fixed!

**Comment by subnut** [comment]
If the bug isn't fixed, reopen this issue. I'm closing it for now.

**Comment by hereGittyGitty** [comment]
Guess we are almost there. :smile:  
Now I get the message
```
[nvim-ghost] : Sent /focus?focus=/tmp/nvimyhVaRj/0
```
every time i start an instance of `nvim` where the `/nvimyhVaR/` part changes of course. I am on the most recent commit of the _main_ branch (`ed4c621`) and have
```
let g:nvim_ghost_super_quiet = 1
```
enabled.

**Comment by subnut** [comment]
Yeah, my bad. I introduced a bug trying to fix another bug.

I was thinking... _Hey, this part of code isn't needed anymore, right? Lemme just remove it._  
Turns out, it _was_ needed.

Oh well.  
052df0c

**Comment by subnut** [comment]
Note to self:

I should probably add a lot of comments all over the code. Like, which functions are referenced where, etc. etc.

**Comment by hereGittyGitty** [comment]
Yeah Bro,

we made it! Well you made it... ;)

Thx again!!! :partying_face:
