### ISSUE TITLE
Doesn't work on overleaf

### ISSUE THREAD

**Issue by niveK77pur** [subnut/nvim-ghost.nvim#44]
Hello, now I don't know if this is an issue with GhostText itself, or with this plugin, because I definitely had it working with [vim-ghost](https://github.com/raghur/vim-ghost) previously (the plugin is not working for me anymore, so I can't double check at this point in time).

# The issue

When I focus the text area on Overleaf, I do not see the text appear in neovim. I only see one big line with HTML  which I cannot possibly interact with.

![image](https://user-images.githubusercontent.com/10981161/210788612-d13ed05e-6fcf-469d-a583-ca0b51310644.png)

**Comment by subnut** [comment]
Sorry, but this is an issue with GhostText itself.  

I recommend you to open an issue at GhostText -  
https://github.com/fregante/GhostText/issues/new

**Comment by niveK77pur** [comment]
Thank you very much! And sorry for the wrong report!
