### ISSUE TITLE
Fix for Apple M1

### ISSUE THREAD

**Issue by c0r73x** [subnut/nvim-ghost.nvim#50]
Please set `multiprocessing.set_start_method("fork")` before initializing multiprocessing.Manager. Without this it will spawn an infinite number of subprocesses on Apple M1.

**Comment by gibfahn** [comment]
+1, had to uninstall nvim-ghost as it's crashing my Mac...

**Comment by subnut** [comment]
Try the [`fix-mac`](https://github.com/subnut/nvim-ghost.nvim/tree/fix-mac) branch

If you are using vim-plug -
```vim
Plug 'subnut/nvim-ghost.nvim', #{branch: 'fix-mac'}
```

**Comment by subnut** [comment]
Please try [`v0.3.1`](https://github.com/subnut/nvim-ghost.nvim/releases/tag/v0.3.1) and report any bugs

**Comment by subnut** [comment]
I hope [`v0.4.0`](https://github.com/subnut/nvim-ghost.nvim/releases/tag/v0.4.0) fixes this issue?
