### ISSUE TITLE
Reuse HTTP port for WebSocket

### ISSUE THREAD

**Issue by fregante** [subnut/nvim-ghost.nvim#52]
See:

- https://github.com/fregante/GhostText/issues/272

Relevant code:

https://github.com/subnut/nvim-ghost.nvim/blob/bcebc1fe30a6926165594d5d6fa60a80487bea1f/binary.py#L476-L480

**Comment by subnut** [comment]
In the current state of the code, it's not possible to run both the servers on the same port.

Both the servers that are being used in this binary (`http.server` and `simple-websocket-server`) try to *occupy* the port. So, running two servers on the same port isn't possible.

To do this, I basically need to write a whole HTTP server *and* a WebSocket server *from scratch*, which is a pretty big task that I don't have the time to do right now.
