### ISSUE TITLE
Include lua instructions

### ISSUE THREAD

**Issue by casonadams** [subnut/nvim-ghost.nvim#57]
# using `lazy`

```lua
-- lua/plugins/nvim-ghost.lua
{
  "subnut/nvim-ghost.nvim",
  keys = {
    { "<leader>ug", ":GhostTextStart<cr>", desc = "GhostTextStart", silent = true },

  },
  name = "nvim_ghost",
  config = function()
    vim.api.nvim_create_autocmd('User', {
      group = "nvim_ghost_user_autocommands",
      pattern = "*.com",
      command = 'setfiletype markdown'
    })
  end
}
```

```lua
-- lua/config/options.lua
g.nvim_ghost_autostart = 0 -- with this set to 0 an error will happen with the autocommand being setup.
```

This sets up the plugin to not autostart, but on `<Leader>ug` it will start, and setup the `autocommand` to set the filetype as `markdown`

The nice thing about lazy is is lazy loads plugins.  So this plugin never gets loaded until the `<leader>ug` is executed.

**Comment by subnut** [comment]
I..... I genuinely have no idea what `lazy` is, and how it corresponds to the code mentioned above

Could you please give me some tips about what it is / where I can read about it?

**Comment by casonadams** [comment]
Good point.  It's the latest coolness in the neovim world.  As far as package management goes.

https://github.com/folke/lazy.nvim

Most of the neovim plugins that are actively being maintained have instructions on how to install the plugin via:

[Lazy](https://github.com/folke/lazy.nvim) (lua)
[Packer](https://github.com/wbthomason/packer.nvim) (lua)
[Plug](https://github.com/junegunn/vim-plug) (vim script)

**Comment by subnut** [comment]
Added to wiki -  
https://github.com/subnut/nvim-ghost.nvim/wiki/Installation-and-Configuration#lazynvim

**Comment by subnut** [comment]
Please check once if you can edit the wiki.  
If not, let me know!
