### ISSUE TITLE
Invalid destination path param

### ISSUE THREAD

**Issue by JonasKru** [subnut/nvim-ghost.nvim#58]
I got the following error:

![image](https://github.com/subnut/nvim-ghost.nvim/assets/20394700/cbd43d05-c46e-473c-980d-db5015ea1309)

I removed the `-DestinationPath .` and it worked just fine.

Not sure where the weirdness comes from but maybe this helps someone else.

Nvim 0.9.5
Win10 (also happened on Win11)

**Comment by subnut** [comment]
Could you please run the following output in PowerShell and paste the output here
```ps1
help Expand-Archive
```

Here's what it returns on my system -
![image](https://github.com/subnut/nvim-ghost.nvim/assets/56714626/f23b9165-6b69-496b-b4d3-da9502d0387e)

**Comment by subnut** [comment]
I'm closing this issue for now due to the original poster not having responded for a long time.

If anybody else faces the same problem, or when @JonasKru replies, this issue shall be re-opened.
