### ISSUE TITLE
Submit the text

### ISSUE THREAD

**Issue by aemonge** [subnut/nvim-ghost.nvim#64]
It would be super nice to have the file sent and additional `<CR>` or `submit` when the file is saved

**Comment by subnut** [comment]
Unfortunately, that needs to be implemented by the browser extension first.

If and when the browser extension implements this feature, only then can we call the relevant API provided by it.

So, the proper place for this issue would be https://github.com/fregante/GhostText   

A similar issue has already been raised there:  
https://github.com/fregante/GhostText/issues/298

**Comment by aemonge** [comment]
I see, thanks !
